#!/usr/bin/env python3
"""Embed exact sign SVGs from the RU content into assets/game/sign-textures.js.

The WebView runs offline from bundled assets, so the artwork of every sign the
3D scene can show is inlined as data URIs. Re-run after adding a code below.
"""
import base64, json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parents[2]
CODES = ['2.1', '2.4', '2.5',                      # crossroad priority signs
         '1.6', '1.14',                             # warnings used by overtaking scenes
         '3.1', '3.20', '3.21', '3.24', '3.25',     # no entry, overtaking / speed limits
         '5.1', '5.2', '5.5', '5.7.1', '5.7.2', '5.16', '5.19.1', '5.19.2', '5.21', '5.22', '5.23.1', '5.25', '5.26']  # special prescriptions

signs = json.loads((ROOT / 'assets/countries/ru/questions/signs.json').read_text())
by_code = {code: item for category in signs.values() for code, item in category.items()}
out, aspect = {}, {}
for code in CODES:
    image = ROOT / 'assets/countries/ru' / by_code[code]['image'].removeprefix('./')
    raw = image.read_bytes()
    out[code] = 'data:image/svg+xml;base64,' + base64.b64encode(raw).decode()
    # Plates (5.7.x, 5.23.x …) are wide: keep their real proportions.
    w = re.search(rb' width="([\d.]+)"', raw[:800]); h = re.search(rb' height="([\d.]+)"', raw[:800])
    if w and h and float(w.group(1)) / float(h.group(1)) > 2:
        aspect[code] = round(float(w.group(1)) / float(h.group(1)), 3)
target = ROOT / 'assets/game/sign-textures.js'
target.write_text('// Exact sign artwork from assets/countries/ru/images/signs; embedded for offline WebView.\n'
                  '// Generated by tools/game_content/build_sign_textures.py — do not edit by hand.\n'
                  'window.PDD_SIGN_TEXTURES = ' + json.dumps(out, ensure_ascii=False) + ';\n'
                  'window.PDD_SIGN_ASPECT = ' + json.dumps(aspect) + ';\n')
print(f'{len(out)} sign textures -> {target}')
