#!/usr/bin/env python3
"""Generate expansion packages' intersection questions from exact RU A/B content."""
import json,pathlib
from first_batch import JUNCTIONS
from second_batch import JUNCTIONS as SECOND_JUNCTIONS
JUNCTIONS = {**JUNCTIONS, **SECOND_JUNCTIONS}
ROOT=pathlib.Path(__file__).resolve().parents[2]
q=json.loads((ROOT/'assets/countries/ru/questions/questions_ab.json').read_text())
out=[]; routes={}
for key,d in JUNCTIONS.items():
 t,i=map(int,key.split('_'));s=q['tickets'][t-1]['questions'][i-1];sid='ticket_'+key
 out.append(dict(id=sid,ticket=f'Билет {t} · Вопрос {i}',sourceQuestionId=s['id'],country='ru',category='ab',
                 sourceImage=s['image'],type='intersection',title=s['question'],explanation=s['comment'],pddRule='',
                 options=[a['text'] for a in s['answers']],correctAnswerIndex=next(i for i,a in enumerate(s['answers']) if a['correct']),**d['layout']))
 routes[sid]=d['route']
(ROOT/'assets/game/junction-situations.js').write_text('// Generated by tools/game_content/build_junction_situations.py; do not edit.\nwindow.PDD_EXTRA_SITUATIONS = '+json.dumps(out,ensure_ascii=False,indent=1)+';\nObject.assign(window.PDD_SCENARIO_ROUTES, '+json.dumps(routes,ensure_ascii=False,indent=1)+');\n')
print(len(out),'junction situations')
