export const NOTIFICATIONS_NAV_HTML = `<button class="nav-item" data-feature="notifications"><svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg><span>Уведомления</span></button>`;
export const NOTIFICATIONS_VIEW_HTML = `
<div id="notifications-view" style="display:none">
<style>
.nt-controls{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:20px}.nt-control{background:#fff;border-radius:16px;padding:18px;display:flex;align-items:center;justify-content:space-between;gap:12px}.nt-control strong{display:block;font-size:14px}.nt-control small{display:block;color:var(--text-muted);font-size:12px;margin-top:5px}.nt-switch{appearance:none;width:42px!important;height:25px;flex-shrink:0;background:#dde1e9;border:none!important;border-radius:20px!important;position:relative;cursor:pointer;padding:0!important}.nt-switch:checked{background:var(--primary)}.nt-switch:before{content:'';position:absolute;top:3px;left:3px;width:19px;height:19px;background:#fff;border-radius:50%;transition:transform .15s}.nt-switch:checked:before{transform:translateX(17px)}
.nt-grid{display:grid;grid-template-columns:minmax(320px,1.3fr) minmax(300px,1fr);gap:20px;margin-bottom:20px;align-items:start}.nt-card{background:#fff;padding:24px;border-radius:18px}.nt-card h3{margin:0 0 20px;font-size:16px}.nt-sticky{position:sticky;top:20px}
.nt-field{display:block;margin-bottom:16px}.nt-field>span{display:block;font-size:12px;font-weight:600;color:var(--text-muted);margin-bottom:7px}.nt-field input,.nt-field textarea,.nt-field select{width:100%;box-sizing:border-box;font-family:inherit}.nt-field textarea{resize:vertical;min-height:110px}.nt-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.nt-row3{display:grid;grid-template-columns:90px 1fr;gap:12px}
.nt-section{border-top:1px solid var(--bg);padding-top:18px;margin-top:6px}.nt-section>h4{margin:0 0 14px;font-size:13px;text-transform:uppercase;letter-spacing:.04em;color:var(--text-muted)}
.nt-seg{display:grid;grid-template-columns:repeat(3,1fr);background:var(--bg);border-radius:12px;padding:4px;gap:4px;margin-bottom:18px}.nt-seg label{text-align:center;padding:10px 6px;border-radius:9px;cursor:pointer;font-size:13px;font-weight:600;color:var(--text-muted)}.nt-seg label small{display:block;font-weight:400;font-size:11px;margin-top:2px}.nt-seg input{display:none}.nt-seg label:has(input:checked){background:#fff;color:var(--text);box-shadow:0 1px 3px rgba(0,0,0,.08)}
.nt-swatches{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.nt-swatch{width:28px;height:28px;border-radius:50%;border:3px solid #fff;box-shadow:0 0 0 1px #dde1e9;cursor:pointer;padding:0!important}.nt-swatch.on{box-shadow:0 0 0 2px var(--text)}.nt-swatches input[type=color]{width:34px!important;height:30px;padding:0!important;border:none!important;background:none}
.nt-image{display:flex;gap:10px;align-items:center}.nt-image input[type=url]{flex:1}.nt-thumb{width:54px;height:54px;border-radius:10px;background:var(--bg) center/cover no-repeat;flex-shrink:0}.nt-check{display:flex;gap:10px;align-items:center;font-size:13px;margin-bottom:14px}.nt-check input{width:auto!important}
.nt-preview{background:var(--bg);border-radius:20px;padding:30px 20px;min-height:260px;display:flex;align-items:center;justify-content:center}
.nt-pv-popup{background:#fff;border-radius:22px;width:100%;max-width:300px;overflow:hidden;overflow-wrap:anywhere;box-shadow:0 10px 30px rgba(0,0,0,.12)}.nt-pv-img{width:100%;aspect-ratio:16/9;background:#eef0f4 center/cover no-repeat}.nt-pv-in{padding:20px}.nt-pv-emoji{font-size:34px;line-height:1;margin-bottom:10px}.nt-pv-popup strong{display:block;font-size:17px;line-height:1.35}.nt-pv-popup p{white-space:pre-wrap;line-height:1.5;margin:8px 0 18px;font-size:14px;color:#444}.nt-pv-btn{display:block;width:100%;border-radius:12px;padding:12px;color:#fff;font-weight:600;font-size:14px;text-align:center;box-sizing:border-box}.nt-pv-btn2{display:block;text-align:center;padding:10px 0 0;font-size:13px;color:#777}
.nt-pv-popup.compact .nt-pv-img{width:64px;height:64px;aspect-ratio:auto;border-radius:14px;margin:20px 20px 0}
.nt-pv-banner{background:#fff;border-radius:16px;width:100%;max-width:340px;min-height:164px;display:flex;gap:14px;padding:18px 34px 18px 16px;align-items:center;border-left:5px solid;box-shadow:0 4px 14px rgba(0,0,0,.08);overflow-wrap:anywhere;position:relative;box-sizing:border-box}.nt-pv-banner .nt-pv-thumb{width:76px;height:76px;border-radius:16px;background:#eef0f4 center/cover no-repeat;flex-shrink:0;display:flex;align-items:center;justify-content:center;font-size:34px}.nt-pv-banner strong{display:block;font-size:15px;line-height:1.25}.nt-pv-banner p{margin:5px 0 0;font-size:12.5px;color:#555;line-height:1.38}.nt-pv-banner .nt-pv-link{font-size:12.5px;font-weight:700;margin-top:8px;display:block}.nt-pv-x{position:absolute;top:12px;right:14px;color:#999;font-size:16px}
.nt-pv-push{width:100%;max-width:330px;display:flex;flex-direction:column;gap:14px}.nt-pv-sys{background:rgba(255,255,255,.92);border-radius:18px;padding:12px 14px;box-shadow:0 4px 14px rgba(0,0,0,.08);overflow-wrap:anywhere}.nt-pv-sys header{display:flex;align-items:center;gap:7px;font-size:11px;color:#777;margin-bottom:6px}.nt-pv-sys header i{width:16px;height:16px;border-radius:4px;display:inline-block}.nt-pv-sys .nt-pv-row{display:flex;gap:10px}.nt-pv-sys strong{display:block;font-size:13px}.nt-pv-sys p{margin:2px 0 0;font-size:13px;color:#333;line-height:1.35;white-space:pre-wrap}.nt-pv-sys .nt-pv-thumb{width:40px;height:40px;border-radius:8px;background:#eef0f4 center/cover no-repeat;flex-shrink:0}.nt-pv-sys .nt-pv-big{margin-top:10px;width:100%;aspect-ratio:2/1;border-radius:10px;background:#eef0f4 center/cover no-repeat}.nt-pv-cap{font-size:11px;color:var(--text-muted);text-align:center;margin-bottom:-8px}
.nt-hint{font-size:12px;color:var(--text-muted);line-height:1.6;margin:14px 0 0}.nt-error{color:var(--danger);font-size:13px;min-height:20px;margin-bottom:12px}.nt-card .btn-action.primary,.nt-modal .btn-action.primary{background:var(--primary);color:#fff}.nt-error:empty{display:none}.nt-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.nt-history{width:100%;border-collapse:collapse;font-size:13px}.nt-history td,.nt-history th{padding:14px 10px;text-align:left;border-bottom:1px solid var(--bg);vertical-align:top}.nt-history th{color:var(--text-muted);font-weight:500}.nt-history strong{display:block;margin-bottom:5px}.nt-history small{color:var(--text-muted)}.nt-history .nt-hthumb{width:44px;height:44px;border-radius:9px;background:var(--bg) center/cover no-repeat;display:flex;align-items:center;justify-content:center;font-size:20px}.nt-status{display:inline-flex;border-radius:7px;padding:5px 8px;background:var(--bg);font-size:12px;white-space:nowrap}.nt-status.ok{background:var(--success-subtle);color:var(--success)}.nt-status.bad{background:var(--danger-subtle);color:var(--danger)}.nt-status.test{background:var(--primary-subtle);color:var(--primary);font-weight:700}.nt-table-wrap{overflow:auto}.nt-empty{text-align:center;color:var(--text-muted);padding:30px}.nt-rowbtns{display:flex;gap:6px;flex-wrap:wrap}
.nt-modal{border:0;border-radius:18px;padding:28px;width:min(420px,90vw);color:var(--text)}.nt-modal::backdrop{background:rgba(0,0,0,.35)}.nt-modal p{line-height:1.6;white-space:pre-wrap;overflow-wrap:anywhere}.nt-modal h3{margin-top:0}
@media(max-width:1050px){.nt-controls{grid-template-columns:1fr 1fr}.nt-grid{grid-template-columns:1fr}.nt-sticky{position:static}}@media(max-width:560px){.nt-controls{grid-template-columns:1fr}.nt-row{grid-template-columns:1fr}.nt-card{padding:18px}}
</style>
<div class="nt-controls">
<label class="nt-control"><span><strong>Пуши</strong><small id="nt-provider">Проверка подключения…</small></span><input class="nt-switch" type="checkbox" data-nt-config="pushEnabled" aria-label="Пуши" disabled></label>
<label class="nt-control"><span><strong>Сообщения в приложении</strong><small>Окна и баннеры</small></span><input class="nt-switch" type="checkbox" data-nt-config="popupEnabled" aria-label="Сообщения в приложении" disabled></label>
<label class="nt-control"><span><strong>Напоминание об учёбе</strong><small>Серия занятий · 20:00</small></span><input class="nt-switch" type="checkbox" data-nt-config="streakEnabled" aria-label="Напоминание об учёбе" disabled></label>
<label class="nt-control"><span><strong>Заезды восстановились</strong><small>Напоминание об игре</small></span><input class="nt-switch" type="checkbox" data-nt-config="gameEnabled" aria-label="Заезды восстановились" disabled></label>
</div>
<div id="nt-page-error" class="nt-error" role="alert"></div>
<div class="nt-grid">
<form id="nt-form" class="nt-card"><h3>Новое сообщение</h3>
<div class="nt-seg" id="nt-kind">
<label><input type="radio" name="nt-kind" value="popup" checked>Окно<small>поверх главного экрана</small></label>
<label><input type="radio" name="nt-kind" value="banner">Баннер<small>вместо блока статистики</small></label>
<label><input type="radio" name="nt-kind" value="push">Пуш<small>системное уведомление</small></label>
</div>
<div class="nt-row"><label class="nt-field"><span>Получатели</span><select id="nt-audience"><option value="all">Все пользователи</option><option value="test">Только мой аккаунт (тест)</option></select></label><label class="nt-field"><span>Платформа</span><select id="nt-platform"><option value="all">Все платформы</option><option value="ios">iOS</option><option value="android">Android</option><option value="web">Веб</option></select></label></div>
<label class="nt-field" id="nt-target-wrap" style="display:none"><span>Мой аккаунт для теста <small>email или ID аккаунта, под которым вы вошли в приложение</small></span><input id="nt-target" list="nt-users-list" maxlength="120" placeholder="Например: ваш email или google_…" autocomplete="off"><datalist id="nt-users-list"></datalist></label>
<div class="nt-row3"><label class="nt-field"><span>Эмодзи</span><input id="nt-emoji" maxlength="8" placeholder="🎉"></label><label class="nt-field"><span>Заголовок</span><input id="nt-title" maxlength="80" placeholder="Например: Новые вопросы уже в приложении" required></label></div>
<label class="nt-field"><span>Текст <small id="nt-count">0 / 1 000</small></span><textarea id="nt-body" maxlength="1000" placeholder="Коротко расскажите пользователям о важном" required></textarea></label>
<div class="nt-section"><h4>Оформление</h4>
<label class="nt-field"><span>Картинка <small>JPEG/PNG/WebP, до 1 МБ, лучше 2:1 или 16:9</small></span><div class="nt-image"><div class="nt-thumb" id="nt-thumb"></div><input type="url" id="nt-image" placeholder="https://… или загрузите файл"><input type="file" id="nt-file" accept="image/jpeg,image/png,image/webp,image/gif" hidden><button type="button" class="btn-action" id="nt-upload">Загрузить</button><button type="button" class="btn-action" id="nt-image-clear" title="Убрать">✕</button></div></label>
<div class="nt-row"><label class="nt-field" id="nt-layout-wrap"><span>Макет</span><select id="nt-layout"><option value="standard">Картинка сверху</option><option value="compact">Компактно (иконка)</option><option value="cover">Крупная обложка</option></select></label>
<div class="nt-field"><span>Цвет акцента</span><div class="nt-swatches" id="nt-swatches"><button type="button" class="nt-swatch" data-color="" style="background:conic-gradient(#ccc 0 25%,#fff 0 50%,#ccc 0 75%,#fff 0)" title="Как в приложении"></button><button type="button" class="nt-swatch" data-color="#1E6FFF" style="background:#1E6FFF"></button><button type="button" class="nt-swatch" data-color="#16A34A" style="background:#16A34A"></button><button type="button" class="nt-swatch" data-color="#F59E0B" style="background:#F59E0B"></button><button type="button" class="nt-swatch" data-color="#DC2626" style="background:#DC2626"></button><button type="button" class="nt-swatch" data-color="#7C3AED" style="background:#7C3AED"></button><input type="color" id="nt-accent" value="#1E6FFF" title="Свой цвет"></div></div></div>
</div>
<div class="nt-section"><h4>Кнопка и действие</h4>
<div class="nt-row"><label class="nt-field"><span>По нажатию</span><select id="nt-action"><option value="none">Просто закрыть</option><option value="url">Открыть ссылку</option><option value="tickets">Открыть билеты</option><option value="topics">Открыть темы</option><option value="game">Открыть игру</option><option value="feed">Открыть ленту</option><option value="settings">Открыть настройки</option></select></label><label class="nt-field" id="nt-button-wrap"><span>Текст кнопки</span><input id="nt-button" maxlength="24" placeholder="Понятно"></label></div>
<label class="nt-field" id="nt-url-wrap" style="display:none"><span>Ссылка</span><input type="url" id="nt-url" placeholder="https://…"></label>
<label class="nt-field" id="nt-dismiss-wrap"><span>Вторая кнопка <small>необязательно, например «Позже»</small></span><input id="nt-dismiss" maxlength="24" placeholder="Не показывать"></label>
</div>
<div class="nt-section"><h4>Отправка</h4>
<div class="nt-row"><label class="nt-field"><span>Когда</span><input type="datetime-local" id="nt-start" title="Пусто — сразу"></label><label class="nt-field"><span id="nt-days-label">Срок показа</span><select id="nt-days"><option value="1">24 часа</option><option value="3">3 дня</option><option value="7" selected>7 дней</option><option value="30">30 дней</option></select></label></div>
<label class="nt-check" id="nt-inapp-wrap" style="display:none"><input type="checkbox" id="nt-inapp">Дублировать окном в приложении (для тех, кто не разрешил уведомления)</label>
</div>
<div id="nt-editor-error" class="nt-error" role="alert"></div>
<div class="nt-actions"><button class="btn-action primary" id="nt-publish" type="submit">Опубликовать</button><button class="btn-action" id="nt-reset" type="button">Очистить</button><span id="nt-result" role="status" class="nt-hint"></span></div>
</form>
<div class="nt-card nt-sticky"><h3>Предпросмотр</h3><div class="nt-preview" id="nt-preview"></div>
<p class="nt-hint" id="nt-format-hint"></p>
<details class="nt-hint"><summary>Подключение и ограничения</summary><p>В режиме «Только мой аккаунт (тест)» сообщение увидят только устройства, где выполнен вход под указанным email или ID. После проверки нажмите «На всех» в списке ниже, чтобы отправить его всем пользователям. Картинка в пуше на Android показывается всегда, на iOS — при наличии Notification Service Extension в сборке. Статус «Принят Firebase» означает приём сервисом, а не доставку каждому устройству. Пуш нельзя отозвать после отправки.</p></details>
</div></div>
<div class="nt-card"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><h3 style="margin:0">Сообщения</h3><button class="btn-action" id="nt-refresh">Обновить</button></div><div class="nt-table-wrap" id="nt-history"><div class="nt-empty">Загрузка…</div></div></div>
<dialog class="nt-modal" id="nt-confirm"><h3 id="nt-confirm-title"></h3><p id="nt-confirm-body"></p><p class="nt-hint" id="nt-confirm-audience"></p><div class="nt-actions"><button class="btn-action" id="nt-confirm-cancel">Отмена</button><button class="btn-action primary" id="nt-confirm-send">Подтвердить</button></div></dialog>
</div>`;
export const NOTIFICATIONS_CLIENT_JS = `
VIEW_TITLES.notifications = 'Уведомления';
(function(){
var ntConfig=null, ntReady=false, ntBusy=false, ntPending=null, ntAccent='', ntItems=[], ntUsersLoaded=false;
var el=function(id){return document.getElementById('nt-'+id);};
var labels={published:'Показывается',scheduled:'Запланировано',queued:'В очереди',sending:'Отправка не подтверждена',accepted:'Принят Firebase',failed:'Ошибка',unknown:'Доставка неизвестна',expired:'Истёк срок'};
var kinds={popup:'Окно',banner:'Баннер',push:'Пуш'};
var platforms={all:'Все платформы',ios:'iOS',android:'Android',web:'Веб'};
var actions={none:'',url:'Ссылка',tickets:'Билеты',topics:'Темы',game:'Игра',feed:'Лента',settings:'Настройки'};
var limits={popup:1000,banner:200,push:300};
try{var savedTarget=localStorage.getItem('nt-test-target');if(savedTarget)el('target').value=savedTarget;}catch(_){}
function kind(){return document.querySelector('input[name="nt-kind"]:checked').value;}
function setKind(v){document.querySelector('input[name="nt-kind"][value="'+v+'"]').checked=true;}
function bg(url){return url?"background-image:url('"+String(url).replace(/['"()<>]/g,'')+"')":'';}
function fmt(t){return new Date(t).toLocaleString('ru',{timeZone:'Europe/Moscow',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})+' МСК';}
async function api(path,body){var r=await fetch('/api/admin/notifications'+path,{method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});var d=await r.json();if(!r.ok)throw new Error(r.status===401?'Войдите в админку заново':d.error||'Не удалось выполнить запрос');return d;}
async function loadTestUsers(){if(ntUsersLoaded)return;ntUsersLoaded=true;try{var r=await fetch('/api/admin/users');if(!r.ok)return;var d=await r.json();var opts=[];(d.users||[]).slice(0,100).forEach(function(u){if(u.email)opts.push('<option value="'+adminEsc(u.email)+'">'+adminEsc((u.name||'')+' · '+u.id)+'</option>');else if(u.id)opts.push('<option value="'+adminEsc(u.id)+'">'+adminEsc(u.name||'Пользователь')+'</option>');});el('users-list').innerHTML=opts.join('');}catch(_){}}
function accent(){return ntAccent||'#1E6FFF';}
function draft(){var k=kind(),test=el('audience').value==='test';return {kind:k,app:'ru',target:test?el('target').value.trim().toLowerCase():'',title:el('title').value.trim(),body:el('body').value.trim(),emoji:el('emoji').value.trim(),imageUrl:el('image').value.trim(),layout:el('layout').value,accent:ntAccent,buttonText:el('button').value.trim(),dismissText:k==='popup'?el('dismiss').value.trim():'',action:el('action').value,actionUrl:el('action').value==='url'?el('url').value.trim():'',inApp:k==='push'&&el('inapp').checked};}
function renderPreview(){var d=draft(),e=adminEsc,title=e(d.title||'Заголовок сообщения'),body=e(d.body||'Ваш текст появится здесь.'),h='';
if(d.kind==='popup'){var img=d.imageUrl?'<div class="nt-pv-img" style="'+bg(d.imageUrl)+(d.layout==='cover'?';aspect-ratio:4/3':'')+'"></div>':'';h='<div class="nt-pv-popup '+(d.layout==='compact'?'compact':'')+'">'+img+'<div class="nt-pv-in">'+(d.emoji?'<div class="nt-pv-emoji">'+e(d.emoji)+'</div>':'')+'<strong>'+title+'</strong><p>'+body+'</p><span class="nt-pv-btn" style="background:'+accent()+'">'+e(d.buttonText||(d.action==='none'?'Понятно':'Открыть'))+'</span>'+(d.dismissText?'<span class="nt-pv-btn2">'+e(d.dismissText)+'</span>':'')+'</div></div>';}
else if(d.kind==='banner'){h='<div class="nt-pv-banner" style="border-color:'+accent()+'"><div class="nt-pv-thumb" style="'+bg(d.imageUrl)+';background-color:'+accent()+'22">'+(d.imageUrl?'':e(d.emoji||'🔔'))+'</div><div style="flex:1;min-width:0"><strong>'+(d.imageUrl&&d.emoji?e(d.emoji)+' ':'')+title+'</strong><p>'+body+'</p>'+(d.action!=='none'?'<span class="nt-pv-link" style="color:'+accent()+'">'+e(d.buttonText||'Подробнее')+' →</span>':'')+'</div><span class="nt-pv-x">✕</span></div>';}
else{var t=(d.emoji?e(d.emoji)+' ':'')+title;h='<div class="nt-pv-push"><div class="nt-pv-cap">iOS</div><div class="nt-pv-sys"><header><i style="background:'+accent()+'"></i>ПДД · сейчас</header><div class="nt-pv-row"><div style="flex:1;min-width:0"><strong>'+t+'</strong><p>'+body+'</p></div>'+(d.imageUrl?'<div class="nt-pv-thumb" style="'+bg(d.imageUrl)+'"></div>':'')+'</div></div><div class="nt-pv-cap">Android (развёрнуто)</div><div class="nt-pv-sys"><header><i style="background:'+accent()+'"></i><span style="color:'+accent()+'">ПДД</span> · сейчас</header><strong>'+t+'</strong><p>'+body+'</p>'+(d.imageUrl?'<div class="nt-pv-big" style="'+bg(d.imageUrl)+'"></div>':'')+'</div></div>';}
el('preview').innerHTML=h;}
function preview(){var k=kind(),push=k==='push',test=el('audience').value==='test',max=limits[k];el('body').maxLength=max;el('count').textContent=el('body').value.length+' / '+max.toLocaleString('ru');el('publish').textContent=test?'Отправить тест себе':push?(el('start').value?'Запланировать пуш':'Отправить пуш'):(el('start').value?'Запланировать':'Опубликовать');el('platform').querySelector('option[value="web"]').disabled=push;if(push&&el('platform').value==='web')el('platform').value='all';
el('target-wrap').style.display=test?'':'none';if(test)loadTestUsers();
el('layout-wrap').style.display=k==='popup'?'':'none';el('dismiss-wrap').style.display=k==='popup'?'':'none';el('url-wrap').style.display=el('action').value==='url'?'':'none';el('inapp-wrap').style.display=push?'':'none';el('button-wrap').style.display=push&&!el('inapp').checked?'none':'';el('days-label').textContent=push?'Актуален':'Срок показа';
el('thumb').style.backgroundImage=el('image').value?'url("'+el('image').value.replace(/"/g,'')+'")':'';
document.querySelectorAll('.nt-swatch').forEach(function(s){s.classList.toggle('on',s.dataset.color===ntAccent);});
el('format-hint').textContent=test?'Тестовое сообщение придёт только на ваш аккаунт. Убедитесь, что в приложении выполнен вход в этот аккаунт.':push?'Пуш получают пользователи, включившие новости приложения и разрешившие уведомления. Нажатие открывает приложение и выполняет выбранное действие.':k==='banner'?'Баннер показывается на главной вместо блока статистики и имеет точно такой же размер. После закрытия крестиком баннер исчезает и возвращается статистика.':'Окно показывается один раз на устройстве, на главном экране. Экзамен и игра не прерываются.';
el('publish').disabled=ntBusy||!ntConfig||(push?(!ntReady||!ntConfig.pushEnabled):!ntConfig.popupEnabled);renderPreview();}
async function load(){el('page-error').textContent='';try{var d=await api('');ntConfig=d.config;ntReady=d.pushConfigured;el('provider').textContent=ntReady?'Firebase подключён':'Firebase не подключён';document.querySelectorAll('[data-nt-config]').forEach(function(x){x.checked=ntConfig[x.dataset.ntConfig];x.disabled=ntBusy||(x.dataset.ntConfig==='pushEnabled'&&!ntReady);});ntItems=d.messages;render(d.messages);preview();}catch(e){el('page-error').textContent=e.message;}}
function render(items){if(!items.length){el('history').innerHTML='<div class="nt-empty">Сообщений пока нет</div>';return;}var now=Date.now();el('history').innerHTML='<table class="nt-history"><thead><tr><th></th><th>Сообщение</th><th>Получатели</th><th>Статус</th><th></th></tr></thead><tbody>'+items.map(function(m){var expired=m.expiresAt<=now,scheduled=(m.startAt||0)>now,status=expired&&m.kind!=='push'?'Истёк срок':!m.enabled?'Отключено':scheduled&&m.kind!=='push'?'Запланировано':labels[m.status]||m.status;if(m.kind==='push'&&m.status==='queued'&&scheduled)status='Запланирован';var canToggle=!expired&&(m.kind!=='push'||m.status==='queued'||m.inApp);var meta=[kinds[m.kind]||m.kind,m.inApp?'+ окно':'',actions[m.action]?'→ '+actions[m.action]:'',fmt(m.createdAt),scheduled?'старт '+fmt(m.startAt):''].filter(Boolean).join(' · ');var who=m.target?'<span class="nt-status test">Тест</span><div style="margin-top:4px"><strong>'+adminEsc(m.target)+'</strong><small>'+platforms[m.platform]+'</small></div>':'Все пользователи<br><small>'+platforms[m.platform]+'</small>';return '<tr><td><div class="nt-hthumb" style="'+bg(m.imageUrl)+(m.accent?';box-shadow:inset 0 -3px 0 '+m.accent:'')+'">'+(m.imageUrl?'':adminEsc(m.emoji||''))+'</div></td><td><strong>'+adminEsc((m.emoji?m.emoji+' ':'')+m.title)+'</strong><small>'+adminEsc(meta)+'</small>'+(m.error?'<div class="nt-error">'+adminEsc(m.error)+'</div>':'')+'</td><td>'+who+'</td><td><span class="nt-status '+(['accepted','published'].includes(m.status)&&m.enabled&&!expired&&!scheduled?'ok':['failed','unknown','sending'].includes(m.status)?'bad':'')+'">'+adminEsc(status)+'</span></td><td><div class="nt-rowbtns">'+(m.target?'<button class="btn-action primary" data-nt-promote="'+m.id+'" title="Скопировать в форму для отправки всем пользователям">На всех</button>':'')+(canToggle?'<button class="btn-action" data-nt-toggle="'+m.id+'" data-enabled="'+(!m.enabled)+'">'+(m.enabled?'Отключить':'Включить')+'</button>':'')+'<button class="btn-action" data-nt-copy="'+m.id+'" title="Создать копию">Копия</button>'+(m.status!=='sending'?'<button class="btn-action" data-nt-delete="'+m.id+'" title="Удалить">✕</button>':'')+'</div></td></tr>';}).join('')+'</tbody></table>';}
function fill(m,forAll){setKind(m.kind);['platform','title','body','emoji','layout','action'].forEach(function(k){if(m[k]!==undefined)el(k).value=m[k];});el('audience').value=forAll?'all':(m.target?'test':'all');if(m.target)el('target').value=m.target;el('image').value=m.imageUrl||'';el('button').value=m.buttonText||'';el('dismiss').value=m.dismissText||'';el('url').value=m.actionUrl||'';el('inapp').checked=!!m.inApp;ntAccent=m.accent||'';el('start').value='';ntPending=null;preview();el('form').scrollIntoView({behavior:'smooth'});}
document.querySelectorAll('[data-nt-config]').forEach(function(x){x.addEventListener('change',async function(){if(ntBusy)return;ntBusy=true;var next=Object.assign({},ntConfig);next[x.dataset.ntConfig]=x.checked;document.querySelectorAll('[data-nt-config]').forEach(function(y){y.disabled=true;});try{await api('/config',next);}catch(e){el('page-error').textContent=e.message;}finally{ntBusy=false;var error=el('page-error').textContent;await load();if(error)el('page-error').textContent=error;}});});
el('history').addEventListener('click',async function(e){var t=e.target.closest('[data-nt-toggle]'),c=e.target.closest('[data-nt-copy]'),p=e.target.closest('[data-nt-promote]'),d=e.target.closest('[data-nt-delete]');
if(p){var mp=ntItems.find(function(x){return x.id===p.dataset.ntPromote;});if(mp){fill(mp,true);el('result').textContent='Проверьте и нажмите «'+(mp.kind==='push'?'Отправить пуш':'Опубликовать')+'» для рассылки на всех';}return;}
if(c){var m=ntItems.find(function(x){return x.id===c.dataset.ntCopy;});if(m)fill(m,false);return;}
if(d){if(!confirm('Удалить сообщение из списка? Окно/баннер перестанут показываться.'))return;d.disabled=true;try{await api('/delete',{id:d.dataset.ntDelete});await load();}catch(err){el('page-error').textContent=err.message;d.disabled=false;}return;}
if(!t)return;t.disabled=true;try{await api('/toggle',{id:t.dataset.ntToggle,enabled:t.dataset.enabled==='true'});await load();}catch(err){el('page-error').textContent=err.message;t.disabled=false;}});
el('swatches').addEventListener('click',function(e){var s=e.target.closest('.nt-swatch');if(!s)return;ntAccent=s.dataset.color;ntPending=null;preview();});
el('accent').addEventListener('input',function(){ntAccent=el('accent').value.toUpperCase();ntPending=null;preview();});
el('upload').onclick=function(){el('file').click();};
el('image-clear').onclick=function(){el('image').value='';ntPending=null;preview();};
el('file').addEventListener('change',async function(){var f=el('file').files[0];el('file').value='';if(!f)return;el('editor-error').textContent='';if(f.size>1048576){el('editor-error').textContent='Картинка больше 1 МБ — сожмите её';return;}el('upload').disabled=true;el('upload').textContent='Загрузка…';try{var r=await fetch('/api/admin/notifications/image',{method:'POST',headers:{'content-type':f.type},body:f});var d=await r.json();if(!r.ok)throw new Error(d.error||'Не удалось загрузить');el('image').value=d.url;ntPending=null;preview();}catch(err){el('editor-error').textContent=err.message;}finally{el('upload').disabled=false;el('upload').textContent='Загрузить';}});
function onFormEdit(){ntPending=null;el('result').textContent='';preview();}
el('form').addEventListener('input',onFormEdit);el('form').addEventListener('change',onFormEdit);
el('reset').onclick=function(){var saved=el('target').value;el('form').reset();el('target').value=saved;ntAccent='';ntPending=null;el('editor-error').textContent='';preview();};
el('form').addEventListener('submit',function(e){e.preventDefault();el('editor-error').textContent='';if(ntBusy||el('publish').disabled)return;if(el('body').value.length>el('body').maxLength){el('editor-error').textContent='Сократите текст сообщения';return;}
var d=draft();if(el('audience').value==='test'&&!d.target){el('editor-error').textContent='Укажите ваш email или ID аккаунта для теста';el('target').focus();return;}
if(d.target){try{localStorage.setItem('nt-test-target',d.target);}catch(_){}}
if(d.action==='url'&&!/^https:[/][/]/.test(d.actionUrl)){el('editor-error').textContent='Укажите ссылку https:// для кнопки';return;}
var start=el('start').value?new Date(el('start').value).getTime():0;if(start&&start<Date.now()-60000){el('editor-error').textContent='Время старта уже прошло';return;}
if(!ntPending){ntPending=Object.assign(d,{id:crypto.randomUUID(),platform:el('platform').value});if(start)ntPending.startAt=start;ntPending.expiresAt=(start||Date.now())+Number(el('days').value)*86400000;}
el('confirm-title').textContent=(ntPending.emoji?ntPending.emoji+' ':'')+ntPending.title;el('confirm-body').textContent=ntPending.body;el('confirm-audience').textContent=[kinds[ntPending.kind],ntPending.target?'Тест → '+ntPending.target:'Все пользователи',platforms[ntPending.platform],start?'Старт: '+fmt(start):'',ntPending.kind==='push'?'После отправки отозвать нельзя':ntPending.kind==='banner'?'Вместо блока статистики':'Один показ на устройство'].filter(Boolean).join(' · ');el('confirm').showModal();});
el('confirm-cancel').onclick=function(){el('confirm').close();};
el('confirm-send').onclick=async function(){if(ntBusy)return;ntBusy=true;el('confirm-send').disabled=true;preview();try{var saved=el('target').value;await api('/publish',ntPending);ntPending=null;el('form').reset();el('target').value=saved;ntAccent='';el('result').textContent='Готово';el('confirm').close();await load();}catch(e){el('confirm').close();el('editor-error').textContent=e.message;}finally{ntBusy=false;el('confirm-send').disabled=false;document.querySelectorAll('[data-nt-config]').forEach(function(x){x.disabled=x.dataset.ntConfig==='pushEnabled'&&!ntReady;});preview();}};
el('refresh').onclick=load;
document.querySelectorAll('.sidebar-menu .nav-item').forEach(function(btn){btn.addEventListener('click',function(){document.getElementById('notifications-view').style.display=btn.dataset.feature==='notifications'?'block':'none';if(btn.dataset.feature==='notifications')load();});});
preview();
})();
`;
